# .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

on:
  push:
    branches: [ develop ]
  pull_request:
    types: [review_requested, ready_for_review]
    # The branches below must be a subset of the branches above
    branches: [ develop ]

# List of jobs
jobs:
  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        if: github.event.pull_request.draft == false
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}